---
name: Tools - Create Release
# This workflow is used to create new releases.
# It creates a ZIP and P7B bundle of the CER files and generates a proper release description.



# Controls when the workflow will run
"on":
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  #
  release:
    types:
      - released
      - prereleased

permissions:
  contents: read

env:
  release_name: ${{ github.event.release.tag_name }}

# set a custom name for the action view
run-name: Create Release - ${{ github.event.release.tag_name }}        

jobs:
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 1000000

      - name: ZIP certificates
        run: |
          # Create ZIP archive
          cd $GITHUB_WORKSPACE
          zip -r NoSpamProxy_CA_Bundle-${{ env.release_name }}.zip roots intermediaries -i *.cer

      - name: Create P7B certificate bundle
        run: |
          cd $GITHUB_WORKSPACE
          certFiles=();for file in $(find ~+ -iname "*.cer");  do echo ${file}; certFiles+=(-certfile ${file}); done;
          openssl crl2pkcs7 -nocrl "${certFiles[@]}" -outform DER -out NoSpamProxy_CA_Bundle-${{ env.release_name }}.p7b

      - name: Get previous release tag
        id: get-tag
        run: |
          # get previous release tag

          if [ "$(git tag | wc -l)" -gt "1" ]; then
            COMMIT_SHA=$(git rev-list -n 1 $(git tag --sort=-v:refname | head -n 2 | tail -n 1))
            
          else
            COMMIT_SHA=$(git rev-list --max-parents=0 HEAD)
          fi

          echo "commit sha: $COMMIT_SHA"
          echo "commit_sha=$COMMIT_SHAG" >> $GITHUB_OUTPUT


      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
        with:
          base_sha: ${{ steps.get-tag.outputs.commit_sha }}
          sha: ${{ github.event.workflow_run.head_branch }}
          files: |
            **.cer  

      - name: Create release description
        env:
          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
          DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
        run: |
          # create release description
          cd $GITHUB_WORKSPACE
          
          echo "# Added certificates:" >> ReleaseNotes.md
          if [[ -z "${ADDED_FILES}" ]]
          then
            echo "No certificates added in this release." >> ReleaseNotes.md
          else
            for file in ${ADDED_FILES}; do
              echo "- $file  " >> ReleaseNotes.md
            done
          fi

          echo "# Deleted certificates:" >> ReleaseNotes.md
          if [[ -z "${DELETED_FILES}" ]]
          then
            echo "No certificates deleted in this release." >> ReleaseNotes.md
          else
            for file in ${DELETED_FILES}; do
              echo "- $file  " >> ReleaseNotes.md
            done
          fi

      - name: Create release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          name: ${{ env.release_name }}
          tag: ${{ env.release_name }}
          artifacts: "NoSpamProxy_CA_Bundle-${{ env.release_name }}.zip,NoSpamProxy_CA_Bundle-${{ env.release_name }}.p7b"
          bodyFile: "ReleaseNotes.md"
          allowUpdates: "true"  